# HOWTO base64 your secret
# echo -n your_secure_credential | base64
kind: Secret
apiVersion: v1
metadata:
  name: cassandra-password
type: Opaque
data:
  cassandra-username: your_base64_encoded_username
  cassandra-password: your_base64_encoded_password
