#
# Copyright © 2016-2020 The Thingsboard Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

apiVersion: v1
kind: ConfigMap
metadata:
  name: tb-http-transport-config
  namespace: thingsboard
  labels:
    name: tb-http-transport-config
data:
  conf: |
    export JAVA_OPTS="$JAVA_OPTS -Xlog:gc*,heap*,age*,safepoint=debug:file=/var/log/tb-http-transport/${TB_SERVICE_ID}-gc.log:time,uptime,level,tags:filecount=10,filesize=10M"
    export JAVA_OPTS="$JAVA_OPTS -XX:+IgnoreUnrecognizedVMOptions -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/var/log/tb-http-transport/${TB_SERVICE_ID}-heapdump.bin"
    export JAVA_OPTS="$JAVA_OPTS -XX:-UseBiasedLocking -XX:+UseTLAB -XX:+ResizeTLAB -XX:+PerfDisableSharedMem -XX:+UseCondCardMark"
    export JAVA_OPTS="$JAVA_OPTS -XX:+UseG1GC -XX:MaxGCPauseMillis=500 -XX:+UseStringDeduplication -XX:+ParallelRefProcEnabled -XX:MaxTenuringThreshold=10"
    export JAVA_OPTS="$JAVA_OPTS -XX:+ExitOnOutOfMemoryError"
    export LOG_FILENAME=tb-http-transport.out
    export LOADER_PATH=/usr/share/tb-http-transport/conf
  logback: |
    <!DOCTYPE configuration>
    <configuration scan="true" scanPeriod="10 seconds">

        <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
            <encoder>
                <pattern>%d{ISO8601} [%thread] %-5level %logger{36} - %msg%n</pattern>
            </encoder>
        </appender>

        <logger name="org.thingsboard.server" level="INFO" />

        <root level="INFO">
            <appender-ref ref="STDOUT"/>
        </root>

    </configuration>

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tb-http-transport
  namespace: thingsboard
spec:
  serviceName: "tb-http-transport"
  podManagementPolicy: Parallel
  replicas: 3
  selector:
    matchLabels:
      app: tb-http-transport
  template:
    metadata:
      labels:
        app: tb-http-transport
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - tb-http-transport
              topologyKey: "kubernetes.io/hostname"
      volumes:
        - name: tb-http-transport-config
          configMap:
            name: tb-http-transport-config
            items:
              - key: conf
                path:  tb-http-transport.conf
              - key: logback
                path:  logback.xml
      containers:
        - name: server
          imagePullPolicy: Always
          image: thingsboard/tb-http-transport:3.3.2
          ports:
            - containerPort: 8080
              name: http
          resources:
            limits:
              cpu: "1000m"
              memory: 2000Mi
            requests:
              cpu: "500m"
              memory: 500Mi
          env:
            - name: TB_SERVICE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: ZOOKEEPER_ENABLED
              value: "true"
            - name: ZOOKEEPER_URL
              value: "zookeeper:2181"
            - name: HTTP_BIND_ADDRESS
              value: "0.0.0.0"
            - name: HTTP_BIND_PORT
              value: "8080"
            - name: HTTP_REQUEST_TIMEOUT
              value: "60000"
          envFrom:
            - configMapRef:
                name: tb-kafka-config
            - configMapRef:
                name: tb-redis-config
          volumeMounts:
            - mountPath: /config
              name: tb-http-transport-config
          readinessProbe:
            periodSeconds: 20
            tcpSocket:
              port: 8080
          livenessProbe:
            initialDelaySeconds: 120
            periodSeconds: 20
            httpGet:
              path: /actuator
              port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: tb-http-transport
  namespace: thingsboard
spec:
  type: ClusterIP
  selector:
    app: tb-http-transport
  ports:
    - port: 8080
      name: http