apiVersion: v1
kind: Service
metadata:
  name: tb-loadbalancer-external
  namespace: thingsboard
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: tb-node
  ports:
    - port: 80
      targetPort: 8080
      name: http
      protocol: TCP
    - port: 1883
      targetPort: 1883
      name: mqtt
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: tb-coap-loadbalancer-external
  namespace: thingsboard
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: tb-node
  ports:
    - port: 5683
      targetPort: 5683
      name: coap
      protocol: UDP
