#
# ThingsBoard, Inc. ("COMPANY") CONFIDENTIAL
#
# Copyright © 2016-2019 ThingsBoard, Inc. All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains
# the property of ThingsBoard, Inc. and its suppliers,
# if any.  The intellectual and technical concepts contained
# herein are proprietary to ThingsBoard, Inc.
# and its suppliers and may be covered by U.S. and Foreign Patents,
# patents in process, and are protected by trade secret or copyright law.
#
# Dissemination of this information or reproduction of this material is strictly forbidden
# unless prior written permission is obtained from COMPANY.
#
# Access to the source code contained herein is hereby forbidden to anyone except current COMPANY employees,
# managers or contractors who have executed Confidentiality and Non-disclosure agreements
# explicitly covering such access.
#
# The copyright notice above does not evidence any actual or intended publication
# or disclosure  of  this source code, which includes
# information that is confidential and/or proprietary, and is a trade secret, of  COMPANY.
# ANY REPRODUCTION, MODIFICATION, DISTRIBUTION, PUBLIC  PERFORMANCE,
# OR PUBLIC DISPLAY OF OR THROUGH USE  OF THIS  SOURCE CODE  WITHOUT
# THE EXPRESS WRITTEN CONSENT OF COMPANY IS STRICTLY PROHIBITED,
# AND IN VIOLATION OF APPLICABLE LAWS AND INTERNATIONAL TREATIES.
# THE RECEIPT OR POSSESSION OF THIS SOURCE CODE AND/OR RELATED INFORMATION
# DOES NOT CONVEY OR IMPLY ANY RIGHTS TO REPRODUCE, DISCLOSE OR DISTRIBUTE ITS CONTENTS,
# OR TO MANUFACTURE, USE, OR SELL ANYTHING THAT IT  MAY DESCRIBE, IN WHOLE OR IN PART.
#

apiVersion: v1
kind: ConfigMap
metadata:
  name: cassandra-probe-config
  namespace: thingsboard
  labels:
    name: cassandra-probe-config
data:
  probe: |
      if [[ $(nodetool status | grep $POD_IP) == *"UN"* ]]; then
         if [[ $DEBUG ]]; then
            echo "UN";
         fi
         exit 0;
      else
         if [[ $DEBUG ]]; then
            echo "Not Up";
         fi
         exit 1;
      fi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cassandra
  namespace: thingsboard
  labels:
    app: cassandra
spec:
  serviceName: cassandra
  replicas: 3
  selector:
    matchLabels:
      app: cassandra
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      nodeSelector:
        role: cassandra
      imagePullSecrets:
        - name: regcred
      volumes:
      - name: cassandra-probe-config
        configMap:
          name: cassandra-probe-config
          items:
          - key: probe
            path: ready-probe.sh
            mode: 0777
      terminationGracePeriodSeconds: 1800
      containers:
      - name: cassandra
        image: cassandra:5.0.4
        imagePullPolicy: Always
        ports:
        - containerPort: 7000
          name: intra-node
        - containerPort: 7001
          name: tls-intra-node
        - containerPort: 7199
          name: jmx
        - containerPort: 9042
          name: cql
        - containerPort: 9160
          name: thrift
        resources:
          requests:
            cpu: "1500m"
            memory: 2Gi
          limits:
            cpu: "2000m"
            memory: 6Gi
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - nodetool drain
        env:
          - name: CASSANDRA_SEEDS
            value: "cassandra-0.cassandra.thingsboard.svc.cluster.local"
          - name: CASSANDRA_CLUSTER_NAME
            value: "Thingsboard Cluster"
          - name: CASSANDRA_AUTO_BOOTSTRAP
            value: "false"
          - name: CASSANDRA_ENDPOINT_SNITCH
            value: GoogleCloudSnitch
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - /probe/ready-probe.sh
          initialDelaySeconds: 90
          timeoutSeconds: 5
        volumeMounts:
        - name: cassandra-probe-config
          mountPath: /probe
        - name: cassandra-data
          mountPath: /var/lib/cassandra
          readOnly: false
  volumeClaimTemplates:
  - metadata:
      name: cassandra-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 100Gi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cassandra
  name: cassandra
  namespace: thingsboard
spec:
  clusterIP: None
  ports:
    - port: 9042
  selector:
    app: cassandra
---
