apiVersion: v1
kind: Service
metadata:
  name: tb-edge-loadbalancer
  namespace: thingsboard
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: tb-node
  ports:
    - port: 7070
      targetPort: 7070
      name: edge
