apiVersion: v1
kind: Pod
metadata:
  name: dsbulk-count-partitions-tb-once
spec:
  backoffLimit: 1 # one try
  activeDeadlineSeconds: 864000 # 10 days
  containers:
    - name: dsbulk
      image: docker.io/sevlamat/dsbulk:1.8.0-r6-count-custom
      resources:
        requests:
          cpu: 2
          memory: 2Gi
        limits:
          cpu: 2
          memory: 2Gi
      imagePullPolicy: IfNotPresent
      command:
        - /bin/bash
        - -c
        - dsbulk count -logDir /dsbulk/data/logs -cl QUORUM -maxConcurrentQueries 32 -k tb -t ts_kv_partitions_cf -u ${CASSANDRA_USER} -p ${CASSANDRA_PASSWORD} -h cassandra-helm-headless -maxErrors 999888 -verbosity 2 --driver.basic.request.page-size 500 --driver.advanced.continuous-paging.page-size 16777216 --driver.advanced.continuous-paging.page-size-in-bytes true
      env:
        - name: CASSANDRA_SEEDS
          value: cassandra-helm-0.cassandra-helm-headless
        - name: CASSANDRA_USER
          value: cassandra
        - name: CASSANDRA_PASSWORD
          valueFrom:
            secretKeyRef:
              key: cassandra-password
              name: cassandra-secret
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
      volumeMounts:
        - name: dsbulk
          mountPath: /dsbulk/data/
  volumes:
    - name: dsbulk
      persistentVolumeClaim:
        claimName: dsbulk
  restartPolicy: Never