apiVersion: v1
kind: Pod
metadata:
  name: dsbulk-upload-once
spec:
  backoffLimit: 1 # one try
  activeDeadlineSeconds: 864000 # 10 days
  containers:
    - name: dsbulk
      image: docker.io/sevlamat/dsbulk:1.8.0-r6
      resources:
        requests:
          cpu: 2
          memory: 4Gi
        limits:
          cpu: 8
          memory: 6Gi
      imagePullPolicy: IfNotPresent
      command:
        - /bin/bash
        - -c
        - dsbulk unload -timestamp true -ttl true -cl QUORUM -maxConcurrentQueries 3 -maxRecords 200000 -c json -url /dsbulk/data/json -logDir /dsbulk/data/logs --connector.json.compression gzip -k thingsboard -t ts_kv_cf -u ${CASSANDRA_USER} -p ${CASSANDRA_PASSWORD} -h cassandra-helm-headless -maxErrors 999888 -verbosity 2 --driver.basic.request.page-size 500 --driver.advanced.continuous-paging.page-size 16777216 --driver.advanced.continuous-paging.page-size-in-bytes true
      env:
        - name: CASSANDRA_SEEDS
          value: cassandra-helm-0.cassandra-helm-headless.thingsboard.svc.cluster.local
        - name: CASSANDRA_USER
          value: cassandra
        - name: CASSANDRA_PASSWORD
          valueFrom:
            secretKeyRef:
              key: cassandra-password
              name: cassandra-secret
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
      volumeMounts:
        - name: dsbulk
          mountPath: /dsbulk/data/
  volumes:
    - name: dsbulk
      persistentVolumeClaim:
        claimName: dsbulk
  restartPolicy: Always #to prevent Deadline exceeded, because on the particular cluster deadline override by admins to 5 hours