apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-database-secret
  labels:
    {{- include "thingsboard.labels" . | nindent 4 }}  
type: kubernetes.io/basic-auth
stringData:
  username: "{{ .Values.database.user }}"
  password: "{{ .Values.database.password }}"